namespace GarageAI.Application.AI.Orchestration.Contracts;

public sealed class AIResponse
{
    /// <summary>
    /// Indicates whether the request completed successfully.
    /// </summary>
    public bool Success { get; init; }

    /// <summary>
    /// The response generated by the AI platform.
    /// </summary>
    public string Content { get; init; } = string.Empty;

    /// <summary>
    /// Optional error message.
    /// </summary>
    public string? AIError { get; init; }
}